#ifndef _THREAD_PRIOS_H_
#define _THREAD_PRIOS_H_

#define CONSOLE_INIT_PRIO 96
#define BTN_INIT_PRIO 97
#define WIFI_CONNECT_PRIO 98
#define DCC_CONNECT_PRIO 99

#define POTI_THREAD_PRIORITY -10
#define STATE_THREAD_PRIORITY 99
#define SEND_THREAD_PRIORITY 99
#define RECV_THREAD_PRIORITY 99

#endif